### ISSUE TITLE
Documentation on how to backup cluster-mgr based cluster for disaster recovery

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs-clustermgr-prod#4]
We need to publish a doc which will show how a cluster-mgr based cluster can be backed up for disaster recovery.

**Comment by afroDC** [comment]
Sounds good. I believe you only need to backup the `./clustermgr` directory. I will do some testing by switching from one machine to another. Will report my findings.

**Comment by afroDC** [comment]
https://github.com/GluuFederation/cluster-mgr/wiki/Backup-and-Restore-LDAP-Data-Online. 

Will add to official documentation shortly.

**Comment by shmorri** [comment]
This is now added in the operations guide
